version: "3.3"

services:
  url-shortener-mongodb:
    image: mongo
    container_name: url-shortener-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  url-shortener-api:
    build: .
    container_name: url-shortener-api
    ports:
      - "5000:5000"
    depends_on:
      - url-shortener-mongodb

volumes:
  mongodb_data:
